"""Provision the Snowflake role model for QG_GOVERNANCE_MODE=warehouse.

Emits the DDL from the migration checklist in
docs/warehouse-enforced-governance.md, reading the same QG_WAREHOUSE_ROLE_MAP
the server reads so the two cannot drift apart.

Prints the SQL and stops. Nothing runs until you pass --apply, because this is
DDL against a warehouse somebody is paying for.

    export QG_WAREHOUSE_ROLE_MAP='analyst=QG_ANALYST,finance=QG_FINANCE'

    python scripts/snowflake_roles.py \\
        --service-user QUERYGATE_SVC \\
        --grant QG_ANALYST=ANALYTICS.SHARED \\
        --grant QG_FINANCE=ANALYTICS.FINANCE

    python scripts/snowflake_roles.py ... --apply     # pipes to `snow sql`
    python scripts/snowflake_roles.py ... --verify    # checks, changes nothing
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys

# Snowflake unquoted identifiers. Everything below reaches SQL as text, so it is
# matched against this first rather than trusted.
_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_$]*$")


def _ident(value: str, what: str) -> str:
    if not _IDENT.match(value):
        sys.exit(f"error: {what} '{value}' is not a plain Snowflake identifier.")
    return value.upper()


def _qualified(value: str, what: str) -> str:
    parts = value.split(".")
    if len(parts) != 2:
        sys.exit(f"error: {what} '{value}' must be DATABASE.SCHEMA.")
    return ".".join(_ident(part, what) for part in parts)


def _parse_role_map(raw: str) -> dict[str, str]:
    """Same format the server parses: 'idp_role=WAREHOUSE_ROLE,...'."""
    mapping: dict[str, str] = {}
    for item in raw.split(","):
        key, _, value = item.strip().partition("=")
        if key.strip() and value.strip():
            mapping[key.strip()] = value.strip()
    return mapping


def _statements(user: str, grants: dict[str, str], warehouse: str | None) -> list[str]:
    out: list[str] = [
        "-- Generated by scripts/snowflake_roles.py. Review before applying.",
        "USE ROLE SECURITYADMIN;",
        "",
    ]
    for role, schema in grants.items():
        database = schema.split(".")[0]
        out += [
            f"CREATE ROLE IF NOT EXISTS {role};",
            f"GRANT USAGE ON DATABASE {database} TO ROLE {role};",
            f"GRANT USAGE ON SCHEMA {schema} TO ROLE {role};",
            # Views only. The point of this mode is that the audience sees the
            # curated surface, not the tables behind it.
            f"GRANT SELECT ON ALL VIEWS IN SCHEMA {schema} TO ROLE {role};",
            f"GRANT SELECT ON FUTURE VIEWS IN SCHEMA {schema} TO ROLE {role};",
        ]
        if warehouse:
            out.append(f"GRANT USAGE ON WAREHOUSE {warehouse} TO ROLE {role};")
        out += [f"GRANT ROLE {role} TO USER {user};", ""]

    out += [
        "-- The service user must hold every mapped role for role switching to work,",
        "-- which is exactly why secondary roles have to be off: with the ALL default",
        "-- the session activates all of them and `USE ROLE` narrows nothing.",
        "USE ROLE USERADMIN;",
        f"ALTER USER {user} SET DEFAULT_SECONDARY_ROLES = ();",
        "",
    ]
    return out


def _verification(user: str, grants: dict[str, str]) -> list[str]:
    out = [
        "-- Read-only checks. Expect DEFAULT_SECONDARY_ROLES to be ().",
        "-- It is a user property, not a session parameter, so DESC USER is the",
        "-- command that reports it. Needs MONITOR on the user, or USERADMIN.",
        f"DESC USER {user};",
        f"SHOW GRANTS TO USER {user};",
        "",
        "-- Per role: the session must report that role and no secondary roles.",
    ]
    for role in grants:
        out += [
            f"USE ROLE {role};",
            "USE SECONDARY ROLES NONE;",
            f"SELECT '{role}' AS expected, CURRENT_ROLE() AS actual, CURRENT_SECONDARY_ROLES() AS secondary;",
        ]
    return out


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--service-user", required=True, help="the Snowflake user QueryGate connects as")
    parser.add_argument(
        "--grant",
        action="append",
        default=[],
        metavar="ROLE=DATABASE.SCHEMA",
        help="grant a warehouse role SELECT on a schema's views; repeatable",
    )
    parser.add_argument("--warehouse", help="also grant USAGE on this virtual warehouse")
    parser.add_argument(
        "--apply", action="store_true", help="pipe the SQL to `snow sql` instead of printing it"
    )
    parser.add_argument("--verify", action="store_true", help="emit read-only checks rather than DDL")
    parser.add_argument("--connection", help="snow CLI connection name")
    args = parser.parse_args()

    user = _ident(args.service_user, "service user")
    warehouse = _ident(args.warehouse, "warehouse") if args.warehouse else None

    grants: dict[str, str] = {}
    for item in args.grant:
        role, _, schema = item.partition("=")
        if not schema:
            sys.exit(f"error: --grant '{item}' must be ROLE=DATABASE.SCHEMA.")
        grants[_ident(role, "role")] = _qualified(schema, "schema")

    # The whole point of reading the server's map here: a role the server can
    # hand out but that nobody created is a caller who gets refused in
    # production for a reason nothing explains.
    role_map = _parse_role_map(os.environ.get("QG_WAREHOUSE_ROLE_MAP", ""))
    if role_map:
        mapped = {role.upper() for role in role_map.values()}
        missing = sorted(mapped - set(grants))
        extra = sorted(set(grants) - mapped)
        if missing:
            sys.exit(
                f"error: QG_WAREHOUSE_ROLE_MAP names {', '.join(missing)}, but no --grant covers "
                "them. Callers mapped to those roles would be refused at query time."
            )
        for role in extra:
            print(f"-- note: {role} is provisioned but unreachable, no IdP role maps to it", file=sys.stderr)
    else:
        print("-- note: QG_WAREHOUSE_ROLE_MAP is unset, skipping the cross-check", file=sys.stderr)

    if not grants:
        sys.exit("error: nothing to do, pass at least one --grant ROLE=DATABASE.SCHEMA.")

    lines = _verification(user, grants) if args.verify else _statements(user, grants, warehouse)
    sql = "\n".join(lines)

    if not args.apply:
        print(sql)
        print("-- not applied. Re-run with --apply once this looks right.", file=sys.stderr)
        return

    if shutil.which("snow") is None:
        sys.exit("error: --apply needs the Snowflake CLI on PATH (pip install snowflake-cli).")
    command = ["snow", "sql", "--stdin"]
    if args.connection:
        command += ["--connection", args.connection]
    result = subprocess.run(command, input=sql, text=True, check=False)  # noqa: S603
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
